xcodeproj 'VLCRemoteKitTests'
inhibit_all_warnings!

def import_pods
  pod 'OCMock', '~> 2.0'
  pod 'VLCRemoteKit', :path => '../'
end

target :ios do
  platform :ios, '7.0'
  link_with 'iOSTests'
  import_pods
end

target :osx do
  platform :osx, '10.9'
  link_with 'OSXTests'
  import_pods
end

post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ARCHS'] = "$(ARCHS_STANDARD_INCLUDING_64_BIT)"
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
